spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/pi?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
  #jpa:
    #database: mysql
    #hibernate:
      #ddl-auto: update
    #show-sql: true
#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chen.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true