spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/pi?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai

  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-idle: 10
      min-idle: 0
      max-wait: -1
      max-active: 200
#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chen.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true